WARNING - 2023-10-09 07:28:53 --> [DEPRECATED] Creation of dynamic property App\Controllers\Test::$db is deprecated in APPPATH\Controllers\Test.php on line 40.
 1 SYSTEMPATH\CodeIgniter.php(891): App\Controllers\Test->__construct()
 2 SYSTEMPATH\CodeIgniter.php(485): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
WARNING - 2023-10-09 07:29:15 --> [DEPRECATED] Creation of dynamic property App\Controllers\Test::$db is deprecated in APPPATH\Controllers\Test.php on line 40.
 1 SYSTEMPATH\CodeIgniter.php(891): App\Controllers\Test->__construct()
 2 SYSTEMPATH\CodeIgniter.php(485): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-09 07:29:16 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'Practice_codeig...', 3306, '', 0)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codeigniter4\app\Controllers\Test.php(49): CodeIgniter\Database\BaseConnection->query('Insert into inf...')
#4 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
#5 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
#6 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codeigniter4\app\Controllers\Test.php(49): CodeIgniter\Database\BaseConnection->query('Insert into inf...')
#3 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
#4 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
#5 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2023-10-09 07:29:16 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\Test.php(49): CodeIgniter\Database\BaseConnection->query('Insert into information_schema(Name,Email) values(\'Karan\',\'Karan@gmail.com\')')
 3 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
 4 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
 5 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
WARNING - 2023-10-09 07:37:51 --> [DEPRECATED] Creation of dynamic property App\Controllers\Test::$db is deprecated in APPPATH\Controllers\Test.php on line 40.
 1 SYSTEMPATH\CodeIgniter.php(891): App\Controllers\Test->__construct()
 2 SYSTEMPATH\CodeIgniter.php(485): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-09 07:37:51 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'Practice_codeig...', 3306, '', 0)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codeigniter4\app\Controllers\Test.php(49): CodeIgniter\Database\BaseConnection->query('Insert into inf...')
#4 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
#5 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
#6 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codeigniter4\app\Controllers\Test.php(49): CodeIgniter\Database\BaseConnection->query('Insert into inf...')
#3 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
#4 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
#5 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2023-10-09 07:37:51 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\Test.php(49): CodeIgniter\Database\BaseConnection->query('Insert into information_schema(Name,Email) values(\'Karan\',\'Karan@gmail.com\')')
 3 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
 4 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
 5 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
WARNING - 2023-10-09 07:37:52 --> [DEPRECATED] Creation of dynamic property App\Controllers\Test::$db is deprecated in APPPATH\Controllers\Test.php on line 40.
 1 SYSTEMPATH\CodeIgniter.php(891): App\Controllers\Test->__construct()
 2 SYSTEMPATH\CodeIgniter.php(485): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-09 07:37:52 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'Practice_codeig...', 3306, '', 0)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codeigniter4\app\Controllers\Test.php(49): CodeIgniter\Database\BaseConnection->query('Insert into inf...')
#4 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
#5 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
#6 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codeigniter4\app\Controllers\Test.php(49): CodeIgniter\Database\BaseConnection->query('Insert into inf...')
#3 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
#4 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
#5 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2023-10-09 07:37:52 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\Test.php(49): CodeIgniter\Database\BaseConnection->query('Insert into information_schema(Name,Email) values(\'Karan\',\'Karan@gmail.com\')')
 3 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
 4 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
 5 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
WARNING - 2023-10-09 07:37:53 --> [DEPRECATED] Creation of dynamic property App\Controllers\Test::$db is deprecated in APPPATH\Controllers\Test.php on line 40.
 1 SYSTEMPATH\CodeIgniter.php(891): App\Controllers\Test->__construct()
 2 SYSTEMPATH\CodeIgniter.php(485): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-09 07:37:53 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'Practice_codeig...', 3306, '', 0)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codeigniter4\app\Controllers\Test.php(49): CodeIgniter\Database\BaseConnection->query('Insert into inf...')
#4 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
#5 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
#6 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codeigniter4\app\Controllers\Test.php(49): CodeIgniter\Database\BaseConnection->query('Insert into inf...')
#3 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
#4 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
#5 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2023-10-09 07:37:53 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\Test.php(49): CodeIgniter\Database\BaseConnection->query('Insert into information_schema(Name,Email) values(\'Karan\',\'Karan@gmail.com\')')
 3 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
 4 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
 5 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
WARNING - 2023-10-09 07:38:11 --> [DEPRECATED] Creation of dynamic property App\Controllers\Test::$db is deprecated in APPPATH\Controllers\Test.php on line 40.
 1 SYSTEMPATH\CodeIgniter.php(891): App\Controllers\Test->__construct()
 2 SYSTEMPATH\CodeIgniter.php(485): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-09 07:38:11 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'Practice_codeig...', 3306, '', 0)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codeigniter4\app\Controllers\Test.php(49): CodeIgniter\Database\BaseConnection->query('Insert into inf...')
#4 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
#5 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
#6 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codeigniter4\app\Controllers\Test.php(49): CodeIgniter\Database\BaseConnection->query('Insert into inf...')
#3 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
#4 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
#5 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2023-10-09 07:38:11 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\Test.php(49): CodeIgniter\Database\BaseConnection->query('Insert into information_schema(Name,Email) values(\'Karan\',\'Karan@gmail.com\')')
 3 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
 4 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
 5 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
WARNING - 2023-10-09 07:39:16 --> [DEPRECATED] Creation of dynamic property App\Controllers\Test::$db is deprecated in APPPATH\Controllers\Test.php on line 9.
 1 SYSTEMPATH\CodeIgniter.php(891): App\Controllers\Test->__construct()
 2 SYSTEMPATH\CodeIgniter.php(485): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-09 07:39:16 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'Practice_codeig...', 3306, '', 0)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codeigniter4\app\Controllers\Test.php(53): CodeIgniter\Database\BaseConnection->query('Insert into inf...')
#4 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
#5 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
#6 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codeigniter4\app\Controllers\Test.php(53): CodeIgniter\Database\BaseConnection->query('Insert into inf...')
#3 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
#4 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
#5 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2023-10-09 07:39:16 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\Test.php(53): CodeIgniter\Database\BaseConnection->query('Insert into information_schema(Name,Email) values(\'Karan\',\'Karan@gmail.com\')')
 3 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
 4 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
 5 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
WARNING - 2023-10-09 07:39:18 --> [DEPRECATED] Creation of dynamic property App\Controllers\Test::$db is deprecated in APPPATH\Controllers\Test.php on line 9.
 1 SYSTEMPATH\CodeIgniter.php(891): App\Controllers\Test->__construct()
 2 SYSTEMPATH\CodeIgniter.php(485): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-09 07:39:18 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'Practice_codeig...', 3306, '', 0)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codeigniter4\app\Controllers\Test.php(53): CodeIgniter\Database\BaseConnection->query('Insert into inf...')
#4 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
#5 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
#6 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codeigniter4\app\Controllers\Test.php(53): CodeIgniter\Database\BaseConnection->query('Insert into inf...')
#3 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
#4 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
#5 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2023-10-09 07:39:18 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\Test.php(53): CodeIgniter\Database\BaseConnection->query('Insert into information_schema(Name,Email) values(\'Karan\',\'Karan@gmail.com\')')
 3 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
 4 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
 5 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
WARNING - 2023-10-09 07:39:51 --> [DEPRECATED] Creation of dynamic property App\Controllers\Test::$db is deprecated in APPPATH\Controllers\Test.php on line 53.
 1 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
 2 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-09 07:39:51 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'Practice_codeig...', 3306, '', 0)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codeigniter4\app\Controllers\Test.php(56): CodeIgniter\Database\BaseConnection->query('Insert into inf...')
#4 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
#5 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
#6 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codeigniter4\app\Controllers\Test.php(56): CodeIgniter\Database\BaseConnection->query('Insert into inf...')
#3 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
#4 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
#5 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2023-10-09 07:39:51 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\Test.php(56): CodeIgniter\Database\BaseConnection->query('Insert into information_schema(Name,Email) values(\'Karan\',\'Karan@gmail.com\')')
 3 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
 4 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
 5 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
WARNING - 2023-10-09 07:43:04 --> [DEPRECATED] Creation of dynamic property App\Controllers\Test::$db is deprecated in APPPATH\Controllers\Test.php on line 53.
 1 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
 2 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-09 07:43:04 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'Practice_codeig...', 3306, '', 0)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codeigniter4\app\Controllers\Test.php(56): CodeIgniter\Database\BaseConnection->query('Insert into inf...')
#4 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
#5 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
#6 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codeigniter4\app\Controllers\Test.php(56): CodeIgniter\Database\BaseConnection->query('Insert into inf...')
#3 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
#4 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
#5 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2023-10-09 07:43:04 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\Test.php(56): CodeIgniter\Database\BaseConnection->query('Insert into information_schema(Name,Email) values(\'Karan\',\'Karan@gmail.com\')')
 3 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
 4 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
 5 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
WARNING - 2023-10-09 07:45:50 --> [DEPRECATED] Creation of dynamic property App\Controllers\Test::$db is deprecated in APPPATH\Controllers\Test.php on line 9.
 1 SYSTEMPATH\CodeIgniter.php(891): App\Controllers\Test->__construct()
 2 SYSTEMPATH\CodeIgniter.php(485): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-09 07:45:50 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'Practice_codeig...', 3306, '', 0)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codeigniter4\app\Controllers\Test.php(53): CodeIgniter\Database\BaseConnection->query('Insert into inf...')
#4 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
#5 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
#6 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codeigniter4\app\Controllers\Test.php(53): CodeIgniter\Database\BaseConnection->query('Insert into inf...')
#3 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
#4 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
#5 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2023-10-09 07:45:50 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\Test.php(53): CodeIgniter\Database\BaseConnection->query('Insert into information_schema(Name,Email) values(\'Karan\',\'Karan@gmail.com\')')
 3 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
 4 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
 5 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
WARNING - 2023-10-09 07:45:52 --> [DEPRECATED] Creation of dynamic property App\Controllers\Test::$db is deprecated in APPPATH\Controllers\Test.php on line 9.
 1 SYSTEMPATH\CodeIgniter.php(891): App\Controllers\Test->__construct()
 2 SYSTEMPATH\CodeIgniter.php(485): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-09 07:45:52 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'Practice_codeig...', 3306, '', 0)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codeigniter4\app\Controllers\Test.php(53): CodeIgniter\Database\BaseConnection->query('Insert into inf...')
#4 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
#5 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
#6 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codeigniter4\app\Controllers\Test.php(53): CodeIgniter\Database\BaseConnection->query('Insert into inf...')
#3 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
#4 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
#5 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2023-10-09 07:45:52 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\Test.php(53): CodeIgniter\Database\BaseConnection->query('Insert into information_schema(Name,Email) values(\'Karan\',\'Karan@gmail.com\')')
 3 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
 4 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
 5 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
WARNING - 2023-10-09 07:46:03 --> [DEPRECATED] Creation of dynamic property App\Controllers\Test::$db is deprecated in APPPATH\Controllers\Test.php on line 9.
 1 SYSTEMPATH\CodeIgniter.php(891): App\Controllers\Test->__construct()
 2 SYSTEMPATH\CodeIgniter.php(485): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
WARNING - 2023-10-09 07:48:29 --> [DEPRECATED] Creation of dynamic property App\Controllers\Test::$db is deprecated in APPPATH\Controllers\Test.php on line 9.
 1 SYSTEMPATH\CodeIgniter.php(891): App\Controllers\Test->__construct()
 2 SYSTEMPATH\CodeIgniter.php(485): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-09 07:48:29 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'Practice_codeig...', 3306, '', 0)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codeigniter4\app\Controllers\Test.php(53): CodeIgniter\Database\BaseConnection->query('Insert into inf...')
#4 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
#5 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
#6 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codeigniter4\app\Controllers\Test.php(53): CodeIgniter\Database\BaseConnection->query('Insert into inf...')
#3 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
#4 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
#5 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2023-10-09 07:48:29 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\Test.php(53): CodeIgniter\Database\BaseConnection->query('Insert into information_schema(Name,Email) values(\'Karan\',\'Karan@gmail.com\')')
 3 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
 4 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
 5 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
WARNING - 2023-10-09 07:55:43 --> [DEPRECATED] Creation of dynamic property App\Controllers\Test::$db is deprecated in APPPATH\Controllers\Test.php on line 9.
 1 SYSTEMPATH\CodeIgniter.php(891): App\Controllers\Test->__construct()
 2 SYSTEMPATH\CodeIgniter.php(485): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-09 07:55:43 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'Practice_codeig...', 3306, '', 0)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codeigniter4\app\Controllers\Test.php(53): CodeIgniter\Database\BaseConnection->query('Insert into inf...')
#4 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
#5 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
#6 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codeigniter4\app\Controllers\Test.php(53): CodeIgniter\Database\BaseConnection->query('Insert into inf...')
#3 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
#4 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
#5 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2023-10-09 07:55:43 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\Test.php(53): CodeIgniter\Database\BaseConnection->query('Insert into information_schema(Name,Email) values(\'Karan\',\'Karan@gmail.com\')')
 3 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
 4 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
 5 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
WARNING - 2023-10-09 07:55:46 --> [DEPRECATED] Creation of dynamic property App\Controllers\Test::$db is deprecated in APPPATH\Controllers\Test.php on line 9.
 1 SYSTEMPATH\CodeIgniter.php(891): App\Controllers\Test->__construct()
 2 SYSTEMPATH\CodeIgniter.php(485): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-09 07:55:46 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'Practice_codeig...', 3306, '', 0)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codeigniter4\app\Controllers\Test.php(53): CodeIgniter\Database\BaseConnection->query('Insert into inf...')
#4 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
#5 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
#6 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codeigniter4\app\Controllers\Test.php(53): CodeIgniter\Database\BaseConnection->query('Insert into inf...')
#3 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
#4 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
#5 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2023-10-09 07:55:46 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\Test.php(53): CodeIgniter\Database\BaseConnection->query('Insert into information_schema(Name,Email) values(\'Karan\',\'Karan@gmail.com\')')
 3 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
 4 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
 5 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
WARNING - 2023-10-09 07:56:16 --> [DEPRECATED] Creation of dynamic property App\Controllers\Test::$db is deprecated in APPPATH\Controllers\Test.php on line 9.
 1 SYSTEMPATH\CodeIgniter.php(891): App\Controllers\Test->__construct()
 2 SYSTEMPATH\CodeIgniter.php(485): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-09 07:56:16 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'Practice_codeig...', 3306, '', 0)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codeigniter4\app\Controllers\Test.php(53): CodeIgniter\Database\BaseConnection->query('Insert into inf...')
#4 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
#5 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
#6 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codeigniter4\app\Controllers\Test.php(53): CodeIgniter\Database\BaseConnection->query('Insert into inf...')
#3 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
#4 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
#5 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2023-10-09 07:56:16 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\Test.php(53): CodeIgniter\Database\BaseConnection->query('Insert into information_schema(Name,Email) values(\'Karan\',\'Karan@gmail.com\')')
 3 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
 4 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
 5 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
WARNING - 2023-10-09 07:56:37 --> [DEPRECATED] Creation of dynamic property App\Controllers\Test::$db is deprecated in APPPATH\Controllers\Test.php on line 9.
 1 SYSTEMPATH\CodeIgniter.php(891): App\Controllers\Test->__construct()
 2 SYSTEMPATH\CodeIgniter.php(485): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-09 07:56:37 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('127.0.0.1', 'root', Object(SensitiveParameterValue), 'Practice_codeig...', 3306, '', 0)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codeigniter4\app\Controllers\Test.php(53): CodeIgniter\Database\BaseConnection->query('Insert into inf...')
#4 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
#5 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
#6 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codeigniter4\app\Controllers\Test.php(53): CodeIgniter\Database\BaseConnection->query('Insert into inf...')
#3 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
#4 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
#5 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2023-10-09 07:56:37 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\Test.php(53): CodeIgniter\Database\BaseConnection->query('Insert into information_schema(Name,Email) values(\'Karan\',\'Karan@gmail.com\')')
 3 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
 4 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
 5 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
WARNING - 2023-10-09 07:56:39 --> [DEPRECATED] Creation of dynamic property App\Controllers\Test::$db is deprecated in APPPATH\Controllers\Test.php on line 9.
 1 SYSTEMPATH\CodeIgniter.php(891): App\Controllers\Test->__construct()
 2 SYSTEMPATH\CodeIgniter.php(485): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-09 07:56:39 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('127.0.0.1', 'root', Object(SensitiveParameterValue), 'Practice_codeig...', 3306, '', 0)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codeigniter4\app\Controllers\Test.php(53): CodeIgniter\Database\BaseConnection->query('Insert into inf...')
#4 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
#5 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
#6 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codeigniter4\app\Controllers\Test.php(53): CodeIgniter\Database\BaseConnection->query('Insert into inf...')
#3 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
#4 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
#5 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2023-10-09 07:56:39 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\Test.php(53): CodeIgniter\Database\BaseConnection->query('Insert into information_schema(Name,Email) values(\'Karan\',\'Karan@gmail.com\')')
 3 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
 4 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
 5 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
WARNING - 2023-10-09 07:56:40 --> [DEPRECATED] Creation of dynamic property App\Controllers\Test::$db is deprecated in APPPATH\Controllers\Test.php on line 9.
 1 SYSTEMPATH\CodeIgniter.php(891): App\Controllers\Test->__construct()
 2 SYSTEMPATH\CodeIgniter.php(485): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-09 07:56:40 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('127.0.0.1', 'root', Object(SensitiveParameterValue), 'Practice_codeig...', 3306, '', 0)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codeigniter4\app\Controllers\Test.php(53): CodeIgniter\Database\BaseConnection->query('Insert into inf...')
#4 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
#5 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
#6 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codeigniter4\app\Controllers\Test.php(53): CodeIgniter\Database\BaseConnection->query('Insert into inf...')
#3 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
#4 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
#5 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2023-10-09 07:56:40 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\Test.php(53): CodeIgniter\Database\BaseConnection->query('Insert into information_schema(Name,Email) values(\'Karan\',\'Karan@gmail.com\')')
 3 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
 4 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
 5 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
WARNING - 2023-10-09 07:56:40 --> [DEPRECATED] Creation of dynamic property App\Controllers\Test::$db is deprecated in APPPATH\Controllers\Test.php on line 9.
 1 SYSTEMPATH\CodeIgniter.php(891): App\Controllers\Test->__construct()
 2 SYSTEMPATH\CodeIgniter.php(485): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-09 07:56:40 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('127.0.0.1', 'root', Object(SensitiveParameterValue), 'Practice_codeig...', 3306, '', 0)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codeigniter4\app\Controllers\Test.php(53): CodeIgniter\Database\BaseConnection->query('Insert into inf...')
#4 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
#5 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
#6 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codeigniter4\app\Controllers\Test.php(53): CodeIgniter\Database\BaseConnection->query('Insert into inf...')
#3 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
#4 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
#5 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2023-10-09 07:56:40 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\Test.php(53): CodeIgniter\Database\BaseConnection->query('Insert into information_schema(Name,Email) values(\'Karan\',\'Karan@gmail.com\')')
 3 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Test->insert_Raw()
 4 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Test))
 5 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
